---
title: "About me"
description: |
  Professional bio and interests
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am a conservation biologist, currently pursuing a Master's degree at the Bren school at UCSB.

**A little bit about my academic and career history:**

I graduated Magna Cum Laude from UC Davis in 2019 with a Bachelor of Science in Wildlife, Fish, and Conservation Biology and a focus in Wildlife Health. During my undergraduate career, I worked at the UC Davis Road Ecology Center under Dr. Fraser Shilling studying the efficacy of wildlife crossing structures under freeways. In that time, I was listed as a contributor in the published findings for the project and was granted a research fellowship from the National Center for Sustainable Transportation. I also designed two independent research projects in 2018 and 2019 and presented my findings at the UC Davis Undergraduate Research Conference. 

After graduating, I worked with several environmental consulting firms providing biological monitoring for construction and mitigation activities in the Bay Area and wildfire remediation in Big Basin State Forest. I also have extensive field experience, including fieldwork abroad at the Jaguar Conservation Fund in Brazil and the Ann Van Dyk Cheetah Center in South Africa. 

**My interests and what I do now:**

I have primarily tackled problems at the interface of humans and wildlife, focusing on habitat connectivity and reduction of human-wildlife conflict. I am currently specializing in Conservation Planning at the Bren School, and have proposed a project working with the California Department of Fish and Wildlife to examine how climate change and urbanization are affecting conflict with black bears.

I hope to continue advancing the peaceful coexistence of humans and wildlife by promoting sustainable development, reducing human-wildlife conflict, and ensuring habitat connectivity in an ever-developing world.